// Importa as 97 lojas reais do relatório de atendimento (Fort Atacadista 52,
// Brasil Atacadista 15, Atacadão 11, Giassi 12, Comper 7) + campos na loja
// para alocação do promotor (promotor relation) e status.
migrate(
  (app) => {
    // 1. coleção lojas
    if (!app.findCollectionByNameOrId('lojas')) {
      const usersId = '_pb_users_auth_'
      const ownerRule = "@request.auth.id != '' && owner = @request.auth.id"
      const lojas = new Collection({
        name: 'lojas',
        type: 'base',
        listRule: ownerRule,
        viewRule: ownerRule,
        createRule: "@request.auth.id != ''",
        updateRule: ownerRule,
        deleteRule: ownerRule,
        fields: [
          {
            name: 'owner',
            type: 'relation',
            required: true,
            collectionId: usersId,
            cascadeDelete: true,
            maxSelect: 1,
          },
          { name: 'nome', type: 'text', required: true, max: 200 },
          { name: 'rede', type: 'text', max: 80 },
          { name: 'bandeira', type: 'text', max: 120 },
          { name: 'cidade', type: 'text', max: 80 },
          { name: 'estado', type: 'text', max: 2 },
          { name: 'endereco', type: 'text', max: 250 },
          { name: 'bairro', type: 'text', max: 120 },
          { name: 'cep', type: 'text', max: 12 },
          { name: 'contratos', type: 'number' },
          { name: 'visitas_semana', type: 'number' },
          { name: 'minutos_semana', type: 'number' },
          {
            name: 'promotor',
            type: 'relation',
            collectionId: app.findCollectionByNameOrId('promotores').id,
            maxSelect: 1,
          },
          { name: 'status', type: 'select', values: ['ativa', 'inativa'], maxSelect: 1 },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_lojas_owner ON lojas (owner)'],
      })
      app.save(lojas)
    }

    const admin = app.findAuthRecordByEmail('_pb_users_auth_', 'daniel@diretoriapromocoes.com.br')
    const col = app.findCollectionByNameOrId('lojas')

    const LOJAS = [
      [
        '085 - FORT ATACADISTA JARAGUÁ DO SUL',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Jaraguá do Sul',
        'SC',
        'RUA MAX WILHELM, 594',
        '0VILA BAEPENDI',
        '89256000',
        18,
        57.0,
        660.0,
      ],
      [
        '115 - FORT ATACADISTA BALNEARIO CAMBORIU',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Balneário Camboriú',
        'SC',
        'RUA TOCANTINS',
        'ESTADOS',
        '88339035',
        21,
        65.0,
        720.0,
      ],
      [
        '130 - FORT ATACADISTA PALHOÇA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Palhoça',
        'SC',
        'RUA JERUSALÈM',
        'JARDIM AQUARIUS',
        '88133020',
        21,
        75.0,
        750.0,
      ],
      [
        '135 - FORT ATACADISTA BRUSQUE',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Brusque',
        'SC',
        'AVENIDA BEPE ROZA, 3700',
        'CENTRO II',
        '88353130',
        18,
        55.0,
        630.0,
      ],
      [
        '145 - FORT ATACADISTA CAMPECHE',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Florianópolis',
        'SC',
        'RODOVIA FRANCISCO MAGNO VIEIRA, 405',
        'RIO TAVARES',
        '88063700',
        17,
        51.0,
        630.0,
      ],
      [
        '160 - FORT ATACADISTA KOBRASOL',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'São José',
        'SC',
        'RUA CASSOL',
        'KOBRASOL',
        '88102340',
        19,
        59.0,
        690.0,
      ],
      [
        '165 - BRASIL ATACADISTA PALHOÇA BR 101',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Palhoça',
        'SC',
        'RODOVIA BR101, S/N - KM 215,7',
        'ARIRIU',
        '88135016',
        2,
        4.0,
        90.0,
      ],
      [
        '165 - FORT ATACADISTA AVENTUREIRO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Joinville',
        'SC',
        'RUA TUIUTI, 4157',
        'AVENTUREIRO',
        '89226001',
        18,
        57.0,
        630.0,
      ],
      [
        '185 - FORT ATACADISTA IÇARA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Içara',
        'SC',
        'AVENIDA GOVERNADOR CELSO RAMOS',
        'JARDIM DOURADO',
        '88820000',
        17,
        56.0,
        630.0,
      ],
      [
        '190 - BRASIL ATACADISTA RIO DO SUL CENTRO',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Rio do Sul',
        'SC',
        'AVENIDA ARISTILIANO RAMOS, 1377',
        'CENTRO',
        '89160113',
        1,
        3.0,
        60.0,
      ],
      [
        '190 - FORT ATACADISTA PORTO BELO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Porto Belo',
        'SC',
        'AVENIDA GOVERNADOR CELSO RAMOS',
        'JARDIM DOURADO',
        '88210000',
        20,
        61.0,
        690.0,
      ],
      [
        '195 - FORT ATACADISTA BLUMENAU II',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Blumenau',
        'SC',
        'RUA DOUTOR PEDRO ZIMMERMANN, 1511',
        'ITOUPAVAZINHA',
        '89066003',
        21,
        62.0,
        720.0,
      ],
      [
        '210 - FORT ATACADISTA FLORIANÓPOLIS',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Florianópolis',
        'SC',
        'RODOVIA ARMANDO CALIL BULOS, 5504',
        'VARGEM DO BOM JESUS',
        '88056618',
        18,
        54.0,
        660.0,
      ],
      [
        '214 - FORT ATACADISTA CAMBORIU',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Camboriú',
        'SC',
        'RUA JOSÉ FRANCISCO BERNARDES, 490',
        'CENTRO',
        '88340206',
        18,
        53.0,
        660.0,
      ],
      [
        '220 - FORT ATACADISTA TUBARÃO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Tubarão',
        'SC',
        'RUA DEPUTADO OLICES PEDRO DE CALDAS',
        'DEHON',
        '88704296',
        17,
        56.0,
        630.0,
      ],
      [
        '225 - FORT ATACADISTA CORDEIROS',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'RUA DOUTOR REINALDO SCHMITHAUSEN, 1249',
        'CORDEIROS',
        '88310002',
        18,
        55.0,
        630.0,
      ],
      [
        '235 - FORT ATACADISTA CRICIÚMA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Criciúma',
        'SC',
        'AVENIDA CENTENÁRIO, 1151',
        'PINHEIRINHO',
        '88805000',
        19,
        60.0,
        690.0,
      ],
      [
        '240 - FORT ATACADISTA CHAPECÓ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Chapecó',
        'SC',
        'AVENIDA SÃO PEDRO, 1968',
        'JARDINS',
        '89803402',
        19,
        60.0,
        690.0,
      ],
      [
        '250 - FORT ATACADISTA FLORESTA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Joinville',
        'SC',
        'RUA SANTA CATARINA, 3086',
        'FLORESTA',
        '89211300',
        20,
        70.0,
        690.0,
      ],
      [
        '255 - FORT ATACADISTA RIO DO SUL',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Rio do Sul',
        'SC',
        'Rodovia BR-470, 131',
        'Canta Galo',
        '89164900',
        21,
        73.0,
        720.0,
      ],
      [
        '256 - BRASIL ATACADISTA RIO DO SUL BOA ESPERANÇA',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Rio do Sul',
        'SC',
        'ESTRADA BOA ESPERANÇA, 240',
        'PROGRESSO',
        '88163610',
        1,
        3.0,
        60.0,
      ],
      [
        '260 - FORT ATACADISTA LAGES',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Lages',
        'SC',
        'AVENIDA PAPA JOÃO XXIII, 295',
        'PETRÓPOLIS',
        '88505200',
        16,
        54.0,
        600.0,
      ],
      [
        '270 - FORT ATACADISTA INDAIAL',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Indaial',
        'SC',
        'RUA AUGUSTO HASSE',
        'BENEDITO',
        '89130000',
        18,
        53.0,
        630.0,
      ],
      [
        '280 - BRASIL ATACADISTA RIO TAVARES',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Florianópolis',
        'SC',
        'RODOVIA FRANCISCO MAGNO VIEIRA, 373',
        'COSTEIRA DO PIRAJUBAÉ',
        '88048000',
        2,
        4.0,
        90.0,
      ],
      [
        '290 - FORT ATACADISTA BIGUAÇU',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Biguaçu',
        'SC',
        'RUA SETE DE SETEMBRO',
        'CENTRO',
        '88160000',
        16,
        51.0,
        600.0,
      ],
      [
        '295 - FORT ATACADISTA BALNEÁRIO CAMBORIU II',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Balneário Camboriú',
        'SC',
        'AVENIDA MARGINAL LESTE',
        'VILA REAL',
        '88330528',
        19,
        58.0,
        660.0,
      ],
      [
        '299 - BRASIL ATACADISTA SERTÃO',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'São José',
        'SC',
        'RODOVIA SC-281, 2665',
        'SERTÃO DO IMARUIM',
        '88106115',
        1,
        3.0,
        60.0,
      ],
      [
        '305 - FORT ATACADISTA BUCAREIN',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Joinville',
        'SC',
        'RUA CORONEL FRANCISCO GOMES, 788',
        'BUCAREIN',
        '89202252',
        18,
        57.0,
        630.0,
      ],
      [
        '306 - FORT ATACADISTA SÃO JOSÉ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'São José',
        'SC',
        'RUA SEBASTIÃO FURTADO PEREIRA',
        'BARREIROS',
        '88117400',
        19,
        67.0,
        690.0,
      ],
      [
        '310 - FORT ATACADISTA ITAJAI',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'AVENIDA CORONEL MARCOS KONDER, 228',
        'CENTRO',
        '88301301',
        20,
        62.0,
        690.0,
      ],
      [
        '325 - FORT ATACADISTA ITAJAI SÃO JOÃO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'RUA INDAIAL, 1370C',
        'SÃO JOÃO',
        '88304300',
        18,
        55.0,
        630.0,
      ],
      [
        '329 - BRASIL ATACADISTA ITAJAI',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Itajaí',
        'SC',
        'AVENIDA OSVALDO REIS',
        'PRAIA BRAVA',
        '88306600',
        2,
        4.0,
        90.0,
      ],
      [
        '335 - FORT ATACADISTA BARRA VELHA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Barra Velha',
        'SC',
        'RODOVIA GOVERNADOR MÁRIO COVAS',
        '0',
        '88390000',
        18,
        55.0,
        630.0,
      ],
      [
        '337 - BRASIL ATACADISTA BLUMENAU',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Blumenau',
        'SC',
        'RUA DR PEDRO ZIMMERMANN, 2430',
        'ITOUPAVAZINHA',
        '89066000',
        1,
        3.0,
        60.0,
      ],
      [
        '345 - BRASIL ATACADISTA LAGES',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Lages',
        'SC',
        'AVENIDA DAS TORRES, 160',
        'GUARUJA',
        '88521098',
        1,
        3.0,
        60.0,
      ],
      [
        '345 - FORT ATACADISTA CAXIAS',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Caxias do Sul',
        'RS',
        'RUA TRONCA',
        'RIO BRANCO',
        '95010100',
        7,
        21.0,
        240.0,
      ],
      [
        '353 - BRASIL ATACADISTA JOINVILLE',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Joinville',
        'SC',
        'RUA ALBANO SCHMIDT, 1200',
        'BOA VISTA',
        '89205098',
        1,
        3.0,
        60.0,
      ],
      [
        '365 - FORT ATACADISTA SÃO JOSÉ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'São José',
        'SC',
        'RODOVIA BR-101',
        'BARREIROS',
        '88111000',
        21,
        75.0,
        750.0,
      ],
      [
        '370 - FORT ATACADISTA VIAMÃO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Viamão',
        'RS',
        'AVENIDA SENADOR SALGADO FILHO',
        'JARDIM KRAHE',
        '94450000',
        7,
        21.0,
        240.0,
      ],
      [
        '375 - FORT ATACADISTA NAVEGANTES',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Navegantes',
        'SC',
        'RUA VEREADOR NEREU LIBERATO NUNES',
        'SAO DOMINGOS',
        '88370232',
        19,
        58.0,
        660.0,
      ],
      [
        '379 - FORT ATACADISTA FLORIANÓPOLIS JARDIM ATLÂNTICO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Florianópolis',
        'SC',
        'RUA ELESBÃO PINTO DA LUZ',
        'JARDIM ATLÂNTICO',
        '88095500',
        16,
        50.0,
        600.0,
      ],
      [
        '385 - FORT ATACADISTA SÃO BENTO DO SUL',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'São Bento do Sul',
        'SC',
        'RUA JORGE ZIPPERER',
        'CENTRO',
        '89280490',
        16,
        52.0,
        600.0,
      ],
      [
        '395 - FORT ATACADISTA SÃO FRANCISCO DO SUL',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'São Francisco do Sul',
        'SC',
        'RUA BINOT PAULMIER DE GONNEVILLE',
        'ACARAI',
        '89240000',
        18,
        55.0,
        630.0,
      ],
      [
        '396 - BRASIL ATACADISTA PORTO BELO',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Porto Belo',
        'SC',
        'AV GOVERNADOR CELSO RAMOS, 2337',
        'PEREQUE',
        '88210000',
        1,
        3.0,
        60.0,
      ],
      [
        '405 - FORT ATACADISTA JOINVILLE COSTA E SILVA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Joinville',
        'SC',
        'RUA ALMIRANTE JACEGUAY',
        'COSTA E SILVA',
        '89220055',
        18,
        57.0,
        630.0,
      ],
      [
        '409 - BRASIL ATACADISTA ARAQUARI',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Araquari',
        'SC',
        ',7000,BL5',
        'ITINGA',
        '89245000',
        1,
        3.0,
        60.0,
      ],
      [
        '410 - FORT ATACADISTA RIO TAVARES',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Florianópolis',
        'SC',
        'RODOVIA DOUTOR ANTÔNIO LUIZ MOURA GONZAGA',
        'RIO TAVARES',
        '88048301',
        20,
        71.0,
        720.0,
      ],
      [
        '418 - BRASIL ATACADISTA NOVA PALHOÇA',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Palhoça',
        'SC',
        'AVENIDA VIDAL PROCOPIO LOHN, SN',
        'NOVA PALHOÇA',
        '88131551',
        1,
        3.0,
        60.0,
      ],
      [
        '420 - FORT ATACADISTA PENHA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Penha',
        'SC',
        'RODOVIA BETO CARRERO WORLD',
        '0',
        '88385000',
        19,
        58.0,
        660.0,
      ],
      [
        '425 - FORT ATACADISTA DOM BOSCO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'RUA JOSÉ DARCY DA SILVA',
        'RESSACADA',
        '88307324',
        20,
        60.0,
        690.0,
      ],
      [
        '445 - FORT ATACADISTA NOVO HAMBURGO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Novo Hamburgo',
        'RS',
        'RUA VINTE E QUATRO DE MAIO',
        'OPERÁRIO',
        '93315138',
        7,
        21.0,
        240.0,
      ],
      [
        '462 - FORT ATACADISTA PALHOÇA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Palhoça',
        'SC',
        'RUA AMARO FERREIRA DE MACEDO',
        'CENTRO',
        '88130280',
        19,
        67.0,
        690.0,
      ],
      [
        '480 - FORT ATACADISTA BLUMENAU',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Blumenau',
        'SC',
        'VIA EXPRESSA PAUL FRITZ KUEHNRICH',
        'ITOUPAVA NORTE',
        '89052381',
        18,
        55.0,
        630.0,
      ],
      [
        '485 - FORT ATACADISTA ARARANGUÁ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Araranguá',
        'SC',
        'RODOVIA GOVERNADOR MÁRIO COVAS',
        'ALTO FELIZ',
        '88390000',
        17,
        54.0,
        630.0,
      ],
      [
        '51 - BRASIL ATACADISTA BIGUAÇU',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Biguaçu',
        'SC',
        'RUA JOAO COAN, 390',
        'UNIVERSITARIO',
        '88161064',
        1,
        3.0,
        60.0,
      ],
      [
        '545 - FORT ATACADISTA CANOAS',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Canoas',
        'RS',
        'AVENIDA FARROUPILHA',
        'MARECHAL RONDON',
        '92020475',
        7,
        21.0,
        240.0,
      ],
      [
        '585 - FORT SÃO BERNARDO DO CAMPO',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'São Bernardo do Campo',
        'SP',
        'Av. Pery Ronchetti, 500',
        'NOVA PETROPOLIS',
        '09771090',
        4,
        15.0,
        120.0,
      ],
      [
        '590 - FORT ATACADISTA SANTOS',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Santos',
        'SP',
        'AVENIDA NOSSA SENHORA DE FÁTIMA',
        'AREIA BRANCA',
        '11085202',
        5,
        21.0,
        180.0,
      ],
      [
        '60 - BRASIL ATACADISTA IPIRANGA',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'São José',
        'SC',
        'RUA ARNOLDO PEDRO MEIRA,404',
        'IPIRANGA',
        '88111370',
        1,
        3.0,
        60.0,
      ],
      [
        '635 - FORT ATACADISTA JUNDIAÍ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Jundiaí',
        'SP',
        'RUA VISCONDE DE TAUNAY',
        'VILA ARENS II',
        '13202540',
        4,
        15.0,
        120.0,
      ],
      [
        '810 -  FORT ATACADISTA FLORIANÓPOLIS',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Florianópolis',
        'SC',
        'RODOVIA JOSÉ CARLOS DAUX',
        'SANTO ANTÔNIO DE LISBOA',
        '88050001',
        17,
        53.0,
        630.0,
      ],
      [
        '825 - FORT ATACADISTA ITAJAÍ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'Avenida Governador Adolfo Konder, 700',
        'São Vicente',
        '88308002',
        19,
        58.0,
        690.0,
      ],
      [
        '885 - FORT SANTA CRUZ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Santa Cruz do Sul',
        'RS',
        'AVENIDA PAUL HARRIS',
        'CENTRO',
        '96810408',
        7,
        21.0,
        240.0,
      ],
      [
        '905 - FORT ATACADISTA VILA NOVA',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Joinville',
        'SC',
        'RUA XV DE NOVEMBRO',
        'VILA NOVA',
        '89237000',
        21,
        73.0,
        720.0,
      ],
      [
        '945 - FORT ATACADISTA GRAVATAÍ',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Gravataí',
        'SC',
        'AVENIDA DORIVAL CÂNDIDO LUZ DE OLIVEIRA',
        'BOM PRINCÍPIO',
        '94070001',
        7,
        21.0,
        240.0,
      ],
      [
        '95 - BRASIL ATACADISTA INGLESES',
        'BRASIL ATACADISTA',
        'MUNDIALMIX',
        'Florianópolis',
        'SC',
        'RODOVIA ARMANDO CALIL BULOS, 5890',
        'INGLESES DO RIO VERMELHO',
        '88058001',
        2,
        4.0,
        90.0,
      ],
      [
        '960 - FORT ATACADISTA LAGES',
        'FORT ATACADISTA',
        'GRUPO PEREIRA',
        'Lages',
        'SC',
        'RUA GETÚLIO VARGAS',
        'CONTA DINHEIRO',
        '88508620',
        16,
        51.0,
        600.0,
      ],
      [
        'ATACADÃO BIGUAÇU',
        'ATACADÃO',
        'ATACADÃO',
        'Biguaçu',
        'SC',
        'RUA ALEXANDRE SÉRGIO GODINHO, 853',
        'MAR DAS PEDRAS',
        '88160500',
        5,
        13.0,
        210.0,
      ],
      [
        'ATACADÃO BLUMENAU',
        'ATACADÃO',
        'ATACADÃO',
        'Blumenau',
        'SC',
        'RODOVIA BR-470, 3000',
        'SALTO DO NORTE',
        '89065800',
        4,
        10.0,
        180.0,
      ],
      [
        'ATACADÃO CAPOEIRA - FLORIANÓPOLIS',
        'ATACADÃO',
        'ATACADAO',
        'Florianópolis',
        'SC',
        'RUA PARALELA NOVO HORIZONTE, 3530',
        'MONTE CRISTO',
        '88090085',
        5,
        13.0,
        210.0,
      ],
      [
        'ATACADÃO CHAPECÓ',
        'ATACADÃO',
        'ATACADÃO',
        'Chapecó',
        'SC',
        'AVENIDA SENADOR ATTILIO FRANCISCO XAVIER FONTANA - E',
        'ENGENHO BRAUN',
        '89209000',
        4,
        10.0,
        180.0,
      ],
      [
        'ATACADÃO CHAPECÓ - MAXXI',
        'ATACADÃO',
        'ATACADÃO',
        'Chapecó',
        'SC',
        'RUA LÍBIA, 3750',
        'LIDER',
        '89805240',
        4,
        10.0,
        180.0,
      ],
      [
        'ATACADÃO FLORIANÓPOLIS',
        'ATACADÃO',
        'ATACADÃO',
        'Florianópolis',
        'SC',
        'AVENIDA JUSCELINO KUBITSCHEK DE OLIVEIRA, 469',
        'ESTREITO',
        '88070120',
        5,
        13.0,
        210.0,
      ],
      [
        'ATACADÃO ITAJAÍ',
        'ATACADÃO',
        'ATACADÃO',
        'Itajaí',
        'SC',
        'AVENIDA GOVERNADOR ADOLFO KONDER, 555',
        'CIDADE NOVA',
        '88308001',
        4,
        13.0,
        180.0,
      ],
      [
        'ATACADÃO IÇARA',
        'ATACADÃO',
        'ATACADÃO',
        'Içara',
        'SC',
        'RODOVIA SC 445, KM 61,5',
        '0',
        '88820000',
        4,
        10.0,
        180.0,
      ],
      [
        'ATACADÃO JOINVILLE',
        'ATACADÃO',
        'ATACADÃO',
        'Joinville',
        'SC',
        'RODOVIA BR-101, KM 40',
        'GLORIA',
        '89216500',
        4,
        10.0,
        180.0,
      ],
      [
        'ATACADÃO LAGES',
        'ATACADÃO',
        'ATACADÃO',
        'Lages',
        'SC',
        'AVENIDA DOM PEDRO II, 2015',
        'UNIVERSITÁRIO',
        '88509000',
        4,
        10.0,
        180.0,
      ],
      [
        'ATACADÃO SÃO JOSÉ',
        'ATACADÃO',
        'ATACADÃO',
        'São José',
        'SC',
        'RUA JOÃO GRUMICHE, 755',
        'KOBRASOL',
        '88102600',
        5,
        13.0,
        210.0,
      ],
      [
        'COMPER BOMBAS',
        'COMPER',
        'GRUPO PEREIRA',
        'Bombinhas',
        'SC',
        'AVENIDA LEOPOLDO ZARLING, 1473',
        'BOMBAS',
        '88215000',
        13,
        28.0,
        360.0,
      ],
      [
        'COMPER BOMBINHAS CENTRO',
        'COMPER',
        'GRUPO PEREIRA',
        'Bombinhas',
        'SC',
        'AVENIDA VEREADOR MANOEL JOSE DOS SANTOS, 854',
        'CENTRO',
        '00000000',
        12,
        24.0,
        330.0,
      ],
      [
        'COMPER CORDEIROS',
        'COMPER',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'RUA DOUTOR REINALDO SCHMITHAUSEN, 2126',
        'CORDEIROS',
        '88310003',
        13,
        26.0,
        360.0,
      ],
      [
        'COMPER FALCÃO',
        'COMPER',
        'GRUPO PEREIRA',
        'Bombinhas',
        'SC',
        'AVENIDA FALCÃO, 637',
        'BOMBAS',
        '88215000',
        12,
        23.0,
        330.0,
      ],
      [
        'COMPER ITAJAÍ CENTRO',
        'COMPER',
        'GRUPO PEREIRA',
        'Itajaí',
        'SC',
        'AVENIDA SETE DE SETEMBRO, 300',
        'CENTRO',
        '88301200',
        12,
        24.0,
        330.0,
      ],
      [
        'COMPER ITAPEMA',
        'COMPER',
        'GRUPO PEREIRA',
        'Itapema',
        'SC',
        'AVENIDA MARGINAL OESTE, 1620',
        'TABOLEIRO DAS OLIVEIRAS',
        '88220000',
        12,
        23.0,
        330.0,
      ],
      [
        'COMPER MORRINHOS',
        'COMPER',
        'GRUPO PEREIRA',
        'Bombinhas',
        'SC',
        'AVENIDA GIRASSOL, 1209',
        'MORRINHOS',
        '88215000',
        14,
        29.0,
        390.0,
      ],
      [
        'Combo Atacadista - Araranguá',
        'GIASSI',
        'Combo Atacadista - Araranguá',
        'Araranguá',
        'SC',
        'Avenida Presidente João Goulart',
        'Cidade Alta',
        '88901026',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Braço do Norte',
        'GIASSI',
        'Combo Atacadista - Braço do Norte',
        'Braço do Norte',
        'SC',
        'Rodovia SC-108, s/n – São Januário, Braço do Norte/SC',
        '0',
        '88750000',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Criciúma',
        'GIASSI',
        'Combo Atacadista - Criciúma',
        'Criciúma',
        'SC',
        'Rua Anita Garibaldi',
        'Centro',
        '88801020',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Forquilhinha',
        'GIASSI',
        'Combo Atacadista - Forquilhinha',
        'Forquilhinha',
        'SC',
        'Rodovia Gabriel Arns, 5800 – Centro, Forquilhinha/SC',
        '0',
        '88850000',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Içara',
        'GIASSI',
        'Combo Atacadista - Içara',
        'Içara',
        'SC',
        'Rodovia Deputado Paulino Búrigo',
        'Nossa Senhora de Fátima',
        '88823278',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Palhoça',
        'GIASSI',
        'Combo Atacadista - Palhoça',
        'Palhoça',
        'SC',
        'Avenida Gentil Reinaldo Cordioli',
        'Jardim Eldorado',
        '88133500',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Sombrio',
        'GIASSI',
        'Combo Atacadista - Sombrio',
        'Sombrio',
        'SC',
        'ua Francisco Possamai (Marginal da BR-101), 1405 – Januária, Sombrio/SC',
        '0',
        '88960000',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - São José',
        'GIASSI',
        'Combo Atacadista - São José',
        'São José',
        'SC',
        'Rua Menino Júlio Cesar',
        'Nossa Senhora do Rosário',
        '88110639',
        1,
        3.0,
        30.0,
      ],
      [
        'Combo Atacadista - Tubarão',
        'GIASSI',
        'Combo Atacadista - Tubarão',
        'Tubarão',
        'SC',
        'Rua Tereza Martins de Brito',
        'Revoredo',
        '88704730',
        1,
        3.0,
        30.0,
      ],
      [
        'GIASSI AMÉRICA JOINVILLE',
        'GIASSI',
        'GIASSI',
        'Joinville',
        'SC',
        'Rua Doutor João Colin',
        'América',
        '89204000',
        2,
        4.0,
        60.0,
      ],
      [
        'GIASSI BUCAREIN JOINVILLE',
        'GIASSI',
        'GIASSI',
        'Joinville',
        'SC',
        'Rua Inácio Bastos',
        'Bucarein',
        '89202310',
        2,
        4.0,
        60.0,
      ],
      [
        'GIASSI JARAGUÁ DO SUL',
        'GIASSI',
        'GIASSI',
        'Jaraguá do Sul',
        'SC',
        'Rua Expedicionário Gumercindo da Silva',
        'Centro',
        '89252000',
        1,
        3.0,
        30.0,
      ],
    ]

    let n = 0
    for (const [
      nome,
      rede,
      bandeira,
      cidade,
      estado,
      endereco,
      bairro,
      cep,
      contratos,
      visitas,
      minutos,
    ] of LOJAS) {
      // idempotente: não duplica
      try {
        app.findFirstRecordByFilter(
          'lojas',
          'owner = "' + admin.id + '" && nome = "' + nome.replace(/"/g, '') + '"',
        )
        continue
      } catch (_) {}
      const r = new Record(col)
      r.set('owner', admin.id)
      r.set('nome', nome)
      r.set('rede', rede)
      r.set('bandeira', bandeira)
      r.set('cidade', cidade)
      r.set('estado', estado)
      r.set('endereco', endereco)
      r.set('bairro', bairro)
      r.set('cep', cep)
      r.set('contratos', contratos)
      r.set('visitas_semana', visitas)
      r.set('minutos_semana', minutos)
      r.set('status', 'ativa')
      app.save(r)
      n++
    }
    console.log('Lojas importadas: ' + n)
  },
  (app) => {
    console.log('down: 0024 — noop.')
  },
)
